language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3="dev-master as 8.7.0"
    - php: 7.1
      env: TYPO3=^8.7
    - php: 7.1
      env: TYPO3=^7.6
    - php: 7.1
      env: TYPO3="7.x-dev"
    - php: 7.0
      env: TYPO3="dev-master as 8.7.0"
    - php: 7.0
      env: TYPO3=^8.7
    - php: 7.0
      env: TYPO3=^7.6
    - php: 5.6
      env: TYPO3=^7.6
    - php: 5.5
      env: TYPO3=^7.6

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer require typo3/cms="$TYPO3"
  - git checkout composer.json
  - mkdir -p .Build/Web/typo3conf/ext/
  - if [ ! -L .Build/Web/typo3conf/ext/belogin_images ]; then ln -snvf ../../../../. .Build/Web/typo3conf/ext/belogin_images; fi
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
