language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3_VERSION=^9
    - php: 7.3
      env: TYPO3_VERSION=^9
    - php: 7.2
      env: TYPO3_VERSION=^10
    - php: 7.3
      env: TYPO3_VERSION=^10
    - php: 7.4
      env: TYPO3_VERSION=^9
    - php: 7.4
      env: TYPO3_VERSION=^10

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - composer self-update
  - composer --version
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer require "typo3/minimal=${TYPO3_VERSION}"
  # Restore composer.json
  - git checkout composer.json
  #- export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
