<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "login_images"
 *
 * Auto generated by Extension Builder 2017-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Backend Login Images',
    'description' => 'Display random Google Chromecast Background Images at your TYPO3 Backend Login Page.',
    'category' => 'plugin',
    'author' => 'Sven Jürgens',
    'author_email' => 'typo3@blue-side.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.3',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
