<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "login_images"
 *
 * Auto generated by Extension Builder 2017-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Backend Login Images',
    'description' => 'Display random Background Images from different sources at your TYPO3 BackendLogin Page.',
    'category' => 'plugin',
    'author' => 'Sven Jürgens',
    'author_email' => 't3YYYY@blue-side.de',
    'state' => 'stable',
    'version' => '6.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.36-12.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
